"""Strategy 21 (needs an external API key, NOT run for the submitted results): real-looking handwriting from an
image model (Gemini) to widen the recogniser's training distribution beyond fonts.

Only *fictitious* values are sent (sampled from the field grammars of strategy 5) and only generated images come
back: no photo, no crop, no patient data ever leaves the machine. The privacy guard below enforces it in code.

Pipeline (one API call = one sheet of 12 handwritten lines, ~10 kept after checks):
  sample N values -> prompt -> image model -> segment N lines -> keep a line only if the recogniser can read the
  expected text in it (CTC likelihood) -> ink patch (RGBA) -> bank (hw_bank/bank.jsonl + PNGs)
synth_pages.synth_page(..., bank=load_bank(...), bank_p=0.3) then pastes bank patches into the form cells, so the
crops still go through the real degradation + registration pipeline with exact labels.

--dry_run replaces the API call by a font-rendered sheet: every other step (guard, segmentation, verification,
bank, synthesis) runs offline and is covered by test_gemini_handwriting.py.

pip install google-genai ; set GEMINI_API_KEY=...
python gemini_handwriting.py --sheets 300 --out ~/dayone_local/hw_bank [--dry_run] [--model gemini-2.5-flash-image]
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import sys
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

W = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(W / s) for s in ("shared", "strat5", "strat10", "strat11")]
from common import LOCAL, MODELS  # noqa: E402
from privacy_linking import scan_text  # noqa: E402
from vocab import infer_kinds, sample_value  # noqa: E402

PENS = ["blue ballpoint pen", "black ballpoint pen", "dark blue gel pen", "black felt-tip pen", "blue fountain pen"]
WRITERS = ["a hurried nurse", "a careful midwife", "a doctor with fast cursive handwriting",
           "someone writing quickly, slightly slanted", "someone with large rounded letters",
           "someone with small, cramped handwriting"]
PROMPT = ("Photo-realistic top-down scan of a sheet of plain white paper with exactly {n} separate lines of "
          "handwriting written with a {pen} by {writer}. Leave a large empty gap between consecutive lines. "
          "No ruled lines, no margins, no line numbers, no other marks. The lines read exactly, top to bottom:\n{lines}")


class PrivacyError(RuntimeError):
    pass


class Guard:
    """Everything that leaves the machine goes through here.
    * text: only values this process sampled from the grammars, and none may look like an identifier;
    * images: only images the API itself returned in this session (never a file, photo or crop from disk)."""

    def __init__(self):
        self.sampled, self.returned = set(), set()

    def register_value(self, v: str):
        self.sampled.add(v)

    def register_returned(self, png: bytes):
        self.returned.add(hashlib.sha256(png).hexdigest())

    def check_text_request(self, values: list[str], prompt: str):
        for v in values:
            if v not in self.sampled:
                raise PrivacyError(f"value not produced by the synthetic sampler: {v!r}")
            hits = scan_text(v)
            if hits:
                raise PrivacyError(f"identifier-like value refused: {v!r} ({hits})")
        if scan_text(prompt):
            raise PrivacyError("identifier-like content in prompt")

    def check_image_part(self, png: bytes):
        if hashlib.sha256(png).hexdigest() not in self.returned:
            raise PrivacyError("only images generated by the API in this session may be sent back")


def sample_sheet(rng, guard: Guard, n: int, lang_p=(0.6, 0.2, 0.2)):
    kinds = [(k, s) for k, s in infer_kinds()[0].items() if s["kind"] != "free"]
    out = []
    while len(out) < n:
        (t, key), spec = kinds[int(rng.integers(len(kinds)))]
        lang = str(rng.choice(["fr", "en", "ar"], p=lang_p))
        v = sample_value(spec, rng, lang, key)
        if not v or v in ("–",) or scan_text(v):
            continue
        guard.register_value(v)
        out.append(dict(text=v, kind=spec["kind"], t=t, key=key, lang=lang))
    return out


def build_prompt(items, rng):
    lines = "\n".join(f"{x['text']}" for x in items)
    return PROMPT.format(n=len(items), pen=rng.choice(PENS), writer=rng.choice(WRITERS), lines=lines)


def call_image_model(prompt: str, model: str) -> bytes:      # pragma: no cover - needs network + key
    from google import genai
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    resp = client.models.generate_content(model=model, contents=[prompt])
    for part in resp.candidates[0].content.parts:
        if getattr(part, "inline_data", None) and part.inline_data.data:
            return part.inline_data.data
    raise RuntimeError("no image in the response")


def _mime(b: bytes) -> str:
    return "image/png" if b[:4] == b"\x89PNG" else "image/jpeg" if b[:2] == b"\xff\xd8" else "image/webp"


def call_readback(png: bytes, n: int, model: str, guard: Guard) -> list[str]:   # pragma: no cover
    """Optional second check: ask a text model to transcribe the generated sheet (image it produced itself)."""
    guard.check_image_part(png)
    from google import genai
    from google.genai import types
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    resp = client.models.generate_content(
        model=model,
        contents=[types.Part.from_bytes(data=png, mime_type=_mime(png)),
                  f"Transcribe the {n} handwritten lines exactly, top to bottom, as a JSON list of strings."],
        config=types.GenerateContentConfig(response_mime_type="application/json"))
    return json.loads(resp.text)


def dry_run_sheet(items, rng) -> bytes:
    """Offline stand-in for the image model: same lines rendered with a random font + writer style."""
    import synth_pages as sp
    latin, arabic = sp.font_lists(False)
    cov = sp.coverage()
    font = str(latin[int(rng.integers(len(latin)))])
    style = sp.writer_style(rng)
    patches = []
    for x in items:
        fp = str(arabic[0]) if sp.is_arabic(x["text"]) else font
        patches.append(sp.render_text(x["text"], fp, rng.uniform(28, 40), (25, 40, 120), rng, cov[fp], style))
    gap = 45
    Wd = max(p.width for p in patches) + 80
    Hd = sum(p.height for p in patches) + gap * (len(patches) + 1)
    sheet = Image.new("RGB", (Wd, Hd), (246, 244, 238))
    y = gap
    for p in patches:
        sheet.paste(p, (40, y), p)
        y += p.height + gap
    buf = io.BytesIO(); sheet.save(buf, "PNG")
    return buf.getvalue()


def ink_map(rgb: np.ndarray) -> np.ndarray:
    g = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY).astype(np.float32) + 1
    bg = cv2.GaussianBlur(cv2.dilate(g, np.ones((25, 25), np.uint8)), (0, 0), 10)
    return np.clip(1 - g / bg, 0, 1)


def segment_lines(rgb: np.ndarray, n: int):
    """n horizontal ink bands (top to bottom) or None when the sheet does not have exactly n lines."""
    ink = ink_map(rgb) > 0.25
    prof = np.convolve(ink.sum(1).astype(np.float32), np.ones(5) / 5, "same")
    on = prof > max(2.0, 0.02 * prof.max())
    bands, y = [], 0
    while y < len(on):
        if on[y]:
            y0 = y
            while y < len(on) and on[y]:
                y += 1
            bands.append([y0, y])
        y += 1
    merged = []                     # merge bands split by a gap smaller than 1/3 of the typical line height
    for b in bands:
        if merged and b[0] - merged[-1][1] < max(6, 0.33 * np.median([x[1] - x[0] for x in bands])):
            merged[-1][1] = b[1]
        else:
            merged.append(b)
    merged = [b for b in merged if b[1] - b[0] >= 8]
    if len(merged) != n:
        return None
    out = []
    for y0, y1 in merged:
        cols = np.nonzero(ink[y0:y1].any(0))[0]
        x0, x1 = max(0, cols.min() - 6), min(rgb.shape[1], cols.max() + 7)
        out.append(rgb[max(0, y0 - 6):y1 + 6, x0:x1])
    return out


def verify(rec, line_rgb: np.ndarray, text: str, max_cer=0.25, min_lp_per_char=-1.2) -> bool:
    """Image models misspell: keep a line only if the recogniser finds the requested text in it. Used alone only
    without a read-back model: it is biased towards handwriting the recogniser already reads (see build_bank)."""
    from rapidfuzz.distance import Levenshtein
    lp = rec.logprobs([line_rgb])[0]
    greedy = rec.decode(lp)[0].strip()
    cer = Levenshtein.distance(greedy, text) / max(1, len(text))
    return cer <= max_cer or rec.score(lp, text) / max(1, len(text)) >= min_lp_per_char


def to_patch(line_rgb: np.ndarray) -> Image.Image:
    """Ink as an RGBA patch (alpha = darkness), ready to be pasted into a form cell."""
    a = (np.clip(ink_map(line_rgb) * 1.6, 0, 1) * 255).astype(np.uint8)
    rgba = np.dstack([line_rgb, a])
    return Image.fromarray(rgba, "RGBA")


def build_bank(sheets: int, out: Path, model: str, dry_run: bool, per_sheet=12, seed=0, readback_model=None):
    from recognizer import Recognizer
    rng = np.random.default_rng(seed)
    rec = Recognizer(str(MODELS / "crnn_final.pt"))
    guard = Guard()
    out.mkdir(parents=True, exist_ok=True)
    kept = rejected_sheets = rejected_lines = 0
    with open(out / "bank.jsonl", "a", encoding="utf-8") as fl:
        for s in range(sheets):
            items = sample_sheet(rng, guard, per_sheet)
            prompt = build_prompt(items, rng)
            guard.check_text_request([x["text"] for x in items], prompt)
            png = dry_run_sheet(items, rng) if dry_run else call_image_model(prompt, model)
            guard.register_returned(png)
            rgb = np.asarray(Image.open(io.BytesIO(png)).convert("RGB"))
            lines = segment_lines(rgb, len(items))
            if lines is None:
                rejected_sheets += 1
                continue
            rb = call_readback(png, len(items), readback_model, guard) if (readback_model and not dry_run) else None
            for i, (x, im) in enumerate(zip(items, lines)):
                if rb is not None:
                    # the read-back is the real check; the recogniser only guards against a segmentation slip
                    # (a strict recogniser check would drop exactly the unfamiliar hands the bank is for)
                    if i >= len(rb) or rb[i].strip() != x["text"] or not verify(rec, im, x["text"], max_cer=0.6,
                                                                               min_lp_per_char=-4.0):
                        rejected_lines += 1
                        continue
                elif not verify(rec, im, x["text"]):
                    rejected_lines += 1
                    continue
                name = f"s{seed}_{s:05d}_{i:02d}.png"
                to_patch(im).save(out / name)
                fl.write(json.dumps(dict(x, png=name, source="dry_run" if dry_run else model), ensure_ascii=False) + "\n")
                kept += 1
    return dict(kept=kept, rejected_sheets=rejected_sheets, rejected_lines=rejected_lines)


def load_bank(path: Path):
    """{kind: [entry]} with the RGBA patch loaded lazily by synth_pages."""
    bank = {}
    f = Path(path) / "bank.jsonl"
    if not f.exists():
        return bank
    for line in open(f, encoding="utf-8"):
        e = json.loads(line)
        e["path"] = str(Path(path) / e["png"])
        bank.setdefault(e["kind"], []).append(e)
    return bank


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sheets", type=int, default=10)
    ap.add_argument("--out", default=str(LOCAL / "hw_bank"))
    ap.add_argument("--model", default="gemini-2.5-flash-image")
    ap.add_argument("--readback_model", default=None, help="e.g. gemini-2.5-flash (optional second check)")
    ap.add_argument("--dry_run", action="store_true")
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()
    if not a.dry_run and not os.environ.get("GEMINI_API_KEY"):
        sys.exit("GEMINI_API_KEY not set (use --dry_run to test the pipeline offline)")
    print(build_bank(a.sheets, Path(a.out).expanduser(), a.model, a.dry_run, seed=a.seed, readback_model=a.readback_model))


if __name__ == "__main__":
    main()
